package gov.iti.jets.model.entities;
// Generated Apr 3, 2023, 5:27:06 AM by Hibernate Tools 6.1.7.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name="book"
    ,catalog="sakila"
)
public class Book  implements java.io.Serializable {


     private Integer id;
     private String author;
     private String description;
     private String img;
     private short language;
     private String name;
     private String noPages;
     private int price;
     private String quantity;
     private String category;

    public Book() {
    }

    public Book(String author, String description, String img, short language, String name, String noPages, int price, String quantity, String category) {
       this.author = author;
       this.description = description;
       this.img = img;
       this.language = language;
       this.name = name;
       this.noPages = noPages;
       this.price = price;
       this.quantity = quantity;
       this.category = category;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="author", nullable=false, length=255)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    
    @Column(name="description", nullable=false, length=255)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="img", nullable=false, length=255)
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }

    
    @Column(name="language", nullable=false)
    public short getLanguage() {
        return this.language;
    }
    
    public void setLanguage(short language) {
        this.language = language;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="no_pages", nullable=false, length=255)
    public String getNoPages() {
        return this.noPages;
    }
    
    public void setNoPages(String noPages) {
        this.noPages = noPages;
    }

    
    @Column(name="price", nullable=false)
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }

    
    @Column(name="quantity", nullable=false, length=255)
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="category", nullable=false, length=255)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }




}


